[programs.devnet]
project_2_solana_gif_portal_starter_contract = "E1sKKb4RBperWd4uT1o7mXxRovGfmauytybquhsnwY7r"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/Avrahm/.config/solana/id.json"

[scripts]
test = "node tests/project-2-solana-gif-portal-starter-contract.js"
